### ISSUE TITLE
Unable to resolve module `./lib/js-runtime` from `node_modules/@bugsnag/core/event.js`

### ISSUE THREAD

**Issue by invyctus92** [bugsnag/bugsnag-js#1357]
When I compile the release version, I receive the following error: 

react-native bundle --platform ios --dev false --entry-file index.js --bundle-output main.jsbundle

error Unable to resolve module `./lib/js-runtime` from `node_modules/@bugsnag/core/event.js`: 

None of these files exist:
  * node_modules/@bugsnag/core/lib/js-runtime(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/@bugsnag/core/lib/js-runtime/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx). Run CLI with --verbose flag for more details.
Error: Unable to resolve module `./lib/js-runtime` from `node_modules/@bugsnag/core/event.js`: 

None of these files exist:
  * node_modules/@bugsnag/core/lib/js-runtime(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/@bugsnag/core/lib/js-runtime/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/angelo/Documents/app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/angelo/Documents/app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/angelo/Documents/app/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/angelo/Documents/app/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/angelo/Documents/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/angelo/Documents/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/angelo/Documents/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/angelo/Documents/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

### Environment
"@bugsnag/react-native": "7.9.3"
  "react-native": "0.63.4"

**Comment by xander-jones** [comment]
Hey @invyctus92, has the `yarn` or `npm` installation failed? Please can you try deleting the `node_modules` directory, then re-install your modules with `npm install` or `yarn install`, then re-try bundling with `react-native` do you see the same error?

**Comment by JoshuaNewcombeWebill** [comment]
Hello I am currently having the same issue. 

error: Error: Unable to resolve module ./lib/js-runtime from node_modules/@bugsnag/core/event.js: 

None of these files exist:
  * node_modules/@bugsnag/core/lib/js-runtime(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/@bugsnag/core/lib/js-runtime/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
> 1 | const ErrorStackParser = require('./lib/error-stack-parser')
  2 | const StackGenerator = require('stack-generator')
  3 | const hasStack = require('./lib/has-stack')
  4 | const map = require('./lib/es-utils/map')
    at ModuleResolver.resolveDependency (/Users/joshuanewcombe/codeProjects/authModuleEngine/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/Users/joshuanewcombe/codeProjects/authModuleEngine/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at Object.resolve (/Users/joshuanewcombe/codeProjects/authModuleEngine/node_modules/metro/src/lib/transformHelpers.js:271:42)
    at resolve (/Users/joshuanewcombe/codeProjects/authModuleEngine/node_modules/metro/src/DeltaBundler/traverseDependencies.js:571:33)
    at /Users/joshuanewcombe/codeProjects/authModuleEngine/node_modules/metro/src/DeltaBundler/traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/joshuanewcombe/codeProjects/authModuleEngine/node_modules/metro/src/DeltaBundler/traverseDependencies.js:586:33)
    at /Users/joshuanewcombe/codeProjects/authModuleEngine/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/joshuanewcombe/codeProjects/authModuleEngine/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

I have tried deleteing the node modules and package-lock file and reinstalling and I still have the same error.

After looking into this a bit more it seems that it is an issue with the @bugsnag/core 7.9.2 and if I downgrade the version to 7.9.0 it works perfectly

Environment
"@bugsnag/react-native": "7.9.1"
"react-native": "0.63.4"

Thank you for the help.

**Comment by xander-jones** [comment]
Hi @invyctus92, @JoshuaNewcombeWebill. `lib/js-runtime.js` was removed from `@bugsnag/core` in v7.9.2. This is very likely a React Native caching issue. Please can you clear your RN / Metro bundler cache?

`react-native start --reset-cache` should do the trick!

**Comment by JoshuaNewcombeWebill** [comment]
Thank you very much for the assistance. That solved the issue :).

**Comment by xander-jones** [comment]
Great news :) Closing out the issue as I think the above should resolve for @invyctus92, but let us know if it's still causing a problem.
