### ISSUE TITLE
@bugsnag/electron 7.14.0 fails to compile on Azure pipelines Windows 10 

### ISSUE THREAD

**Issue by zac-jacobson** [bugsnag/bugsnag-js#1593]
### Describe the bug
@bugsnag/electron fails to compile on Azure pipelines Windows 10 during `yarn install`

### Steps to reproduce
1. Upgraded existing electron project to us @bugsnag/electron 7.14.0
2. run `yarn install`
2. See error

### Environment
* Bugsnag version: 7.14.0
* Electron 15.3.1
* Electron-forge 6.0.0-beta.61
* Node 16.5.0
* Python 3.8.10, 3.10.0
* Yarn 1.22.5

### Example Azure pipeline error message

<details><summary>Error messages:</summary>

```
[5/5] Building fresh packages...
error D:\a\1\s\node_modules\@bugsnag\plugin-electron-app: Command failed.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: D:\a\1\s\node_modules\@bugsnag\plugin-electron-app
Output:
D:\a\1\s\node_modules\@bugsnag\plugin-electron-app>if not defined npm_config_node_gyp (node "C:\hostedtoolcache\windows\node\16.5.0\x64\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.5.0 | win32 | x64
gyp info find Python using Python version 3.8.10 found at "C:\hostedtoolcache\windows\Python\3.8.10\x64\python3.exe"
gyp http GET https://nodejs.org/download/release/v16.5.0/node-v16.5.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.5.0/node-v16.5.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.5.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v16.5.0/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v16.5.0/win-x64/node.lib
gyp http GET https://nodejs.org/download/release/v16.5.0/win-arm64/node.lib
gyp http 404 https://nodejs.org/download/release/v16.5.0/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v16.5.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v16.5.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v16.5.0/win-x86/node.lib
gyp info find VS using VS2019 (16.11.31829.152) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
gyp info find VS run with --verbose for detailed information
(node:5200) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn C:\hostedtoolcache\windows\Python\3.8.10\x64\python3.exe
gyp info spawn args [
gyp info spawn args   'C:\\hostedtoolcache\\windows\\node\\16.5.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\a\\1\\s\\node_modules\\@bugsnag\\plugin-electron-app\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\hostedtoolcache\\windows\\node\\16.5.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\VssAdministrator\\AppData\\Local\\node-gyp\\Cache\\16.5.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\VssAdministrator\\AppData\\Local\\node-gyp\\Cache\\16.5.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\hostedtoolcache\\windows\\node\\16.5.0\\x64\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\VssAdministrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.5.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\a\\1\\s\\node_modules\\@bugsnag\\plugin-electron-app',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\a\\1\\s\\node_modules\\@bugsnag\\plugin-electron-app\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  api.c
C:\Users\VssAdministrator\AppData\Local\node-gyp\Cache\16.5.0\include\node\node_api.h(12,10): fatal error C1083: Cannot open include file: 'js_native_api.h': No such file or directory [D:\a\1\s\node_modules\@bugsnag\plugin-electron-app\build\bugsnag_plugin_electron_app_bindings.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\hostedtoolcache\windows\node\16.5.0\x64\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\hostedtoolcache\\windows\\node\\16.5.0\\x64\\node.exe" "C:\\hostedtoolcache\\windows\\node\\16.5.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\a\1\s\node_modules\@bugsnag\plugin-electron-app
gyp ERR! node -v v16.5.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
##[error]Cmd.exe exited with code '1'.
Finishing: Yarn install
```
</details>

**Comment by xander-jones** [comment]
Hey @zac-jacobson 👋  to confirm, this working previously with versions < `7.14.0`? Are files getting cached on this machine machine? If you delete the `node_modules` directory with `rd /s "node_modules"` (for Windows), and clear the Yarn cache completely with `yarn cache clean`, and then re-run `yarn install` do you see the same issue?

**Comment by zac-jacobson** [comment]
Hi @xander-jones 

Yes, it works with 7.13.3

I ran the pipeline again with caching off and explicitly called `yarn cache clean`. `yarn install` does still fail, though a slightly different error message:


<details><summary>Azure `yarn install` output</summary>
```
##[section]Starting: Install node_modules
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
yarn install --frozen-lockfile
========================== Starting Command Output ===========================
##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\f629284c-f0fe-4f91-be50-7761d8d745c2.cmd""
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info appdmg@0.6.2: The platform "win32" is incompatible with this module.
info "appdmg@0.6.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fs-xattr@0.3.1: The platform "win32" is incompatible with this module.
info "fs-xattr@0.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info macos-alias@0.2.11: The platform "win32" is incompatible with this module.
info "macos-alias@0.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @bugsnag/plugin-react@7.13.2" has unmet peer dependency "@bugsnag/core@^7.0.0".
warning " > ts-node@10.4.0" has unmet peer dependency "@types/node@*".
[5/5] Building fresh packages...
error D:\a\1\s\node_modules\@bugsnag\plugin-electron-app: Command failed.
Exit code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Command: node-gyp rebuild
Arguments: 
Directory: D:\a\1\s\node_modules\@bugsnag\plugin-electron-app
Output:
D:\a\1\s\node_modules\@bugsnag\plugin-electron-app>if not defined npm_config_node_gyp (node "C:\hostedtoolcache\windows\node\16.5.0\x64\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.5.0 | win32 | x64
gyp info find Python using Python version 3.8.10 found at "C:\hostedtoolcache\windows\Python\3.8.10\x64\python3.exe"
gyp http GET https://nodejs.org/download/release/v16.5.0/node-v16.5.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.5.0/node-v16.5.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.5.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v16.5.0/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v16.5.0/win-x64/node.lib
gyp http GET https://nodejs.org/download/release/v16.5.0/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v16.5.0/win-x64/node.lib
gyp http 404 https://nodejs.org/download/release/v16.5.0/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v16.5.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v16.5.0/win-x86/node.lib
gyp info find VS using VS2019 (16.11.31911.196) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
gyp info find VS run with --verbose for detailed information
(node:1264) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn C:\hostedtoolcache\windows\Python\3.8.10\x64\python3.exe
gyp info spawn args [
gyp info spawn args   'C:\\hostedtoolcache\\windows\\node\\16.5.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\a\\1\\s\\node_modules\\@bugsnag\\plugin-electron-app\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\hostedtoolcache\\windows\\node\\16.5.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\VssAdministrator\\AppData\\Local\\node-gyp\\Cache\\16.5.0\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\VssAdministrator\\AppData\\Local\\node-gyp\\Cache\\16.5.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\hostedtoolcache\\windows\\node\\16.5.0\\x64\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\VssAdministrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.5.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\a\\1\\s\\node_modules\\@bugsnag\\plugin-electron-app',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\a\\1\\s\\node_modules\\@bugsnag\\plugin-electron-app\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: C:\Users\VssAdministrator\AppData\Local\node-gyp\Cache\16.5.0\common.gypi not found (cwd: D:\a\1\s\node_modules\@bugsnag\plugin-electron-app) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\hostedtoolcache\windows\node\16.5.0\x64\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\hostedtoolcache\\windows\\node\\16.5.0\\x64\\node.exe" "C:\\hostedtoolcache\\windows\\node\\16.5.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\a\1\s\node_modules\@bugsnag\plugin-electron-app
gyp ERR! node -v v16.5.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
##[error]Cmd.exe exited with code '1'.
##[section]Finishing: Install node_modules
```
</details>

**Comment by zac-jacobson** [comment]
FYI we are using the [windows-latest hosted agent](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md).

**Comment by xander-jones** [comment]
Hey @zac-jacobson, on the face of it, this looks like the issue may be with `node-gyp`? specifically:
```
gyp: C:\Users\VssAdministrator\AppData\Local\node-gyp\Cache\16.5.0\common.gypi not found (cwd: D:\a\1\s\node_modules\@bugsnag\plugin-electron-app) while reading includes of binding.gyp while trying to load binding.gyp
```
It may be worth updating your version to the latest, or at least giving it a fresh install (it'll be a global dependency). For what it's worth we do [test](https://github.com/bugsnag/bugsnag-js/runs/4238833705?check_suite_focus=true) with the `windows-2019` environment, and these pass as expected, so there shouldn't be any issues here with installing the library.

**Comment by zac-jacobson** [comment]
Thanks for the pointers @xander-jones . We do have node-gyp@8.4.1 in the project, but as you point out, it was the global dependancy that needed to be updated.

I can confirm that running this Azure step before `yarn install`
```
- script: 'npm --verbose install --global node-gyp@8.4.1'
  displayName: 'Bump system node-gyp'
```
Allowed the install to complete successfully.

**Comment by xander-jones** [comment]
🎉  Awesome, glad that sorted it!

**Comment by zac-jacobson** [comment]
Follow up

Sometime after the above discussion, we started having problems again, and just reverted to v7.13.3

Today, though, we discovered that the real problem appears to be with Azure's `Cache` task: it is broken on Windows, and not all modules are reconstituted correctly. To get around this, we added a step after the Cache restoration to delete the directory for this module in particular, and then when `yarn install` run, it is fetches and builds correctly, so now we can finally update this module.
