### ISSUE TITLE
Class constructor ErrorHandler cannot be invoked without 'new'

### ISSUE THREAD

**Issue by kendecat09** [bugsnag/bugsnag-js#1952]
note that i only get this message when i try to create a new user and the message appear both on my browser and vscode terminal.

can someone help please

TypeError: Class constructor ErrorHandler cannot be invoked without 'new'
    at Layer.handle [as handle_request] (E:\Learning Web Development\digitic\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Learning Web Development\digitic\node_modules\express\lib\router\index.js:328:13)
    at E:\Learning Web Development\digitic\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (E:\Learning Web Development\digitic\node_modules\express\lib\router\index.js:346:12)
    at next (E:\Learning Web Development\digitic\node_modules\express\lib\router\index.js:280:10)
    at urlencodedParser (E:\Learning Web Development\digitic\node_modules\body-parser\lib\types\urlencoded.js:100:7)
    at Layer.handle [as handle_request] (E:\Learning Web Development\digitic\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Learning Web Development\digitic\node_modules\express\lib\router\index.js:328:13)
    at E:\Learning Web Development\digitic\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (E:\Learning Web Development\digitic\node_modules\express\lib\router\index.js:346:12)

here is my code...
class ErrorHandler extends Error {
  constructor(message, statusCode) {
    super(message);
    this.statusCode = statusCode;

    Error.captureStackTrace(this, this.constructor);
  }
}

module.exports = ErrorHandler;

**Comment by johnkiely1** [comment]
Hi @kendecat09, unless I'm mistaken this does not look to be related to Bugsnag so is not the right place to ask a question like this. 

The guide for integrating Bugsnag with Express is here: https://docs.bugsnag.com/platforms/javascript/express/

For more general Express JS related queries such as this I would suggest going directly to the creators: https://github.com/expressjs/express
