### ISSUE TITLE
Angular 17 app can't run with bugsnag/plugin-angular and esbuild

### ISSUE THREAD

**Issue by mivanyna** [bugsnag/bugsnag-js#2057]
### Describe the bug
Angular app fails on start with error `Class constructor ErrorHandler cannot be invoked without 'new'`

### Steps to reproduce
1. Have in app.module setup like in documentation:
```
export function errorHandlerFactory() {
  return new BugsnagErrorHandler()
}

```
In the module providers:
```
{ provide: ErrorHandler, useFactory: errorHandlerFactory },
```
2. Set `"builder": "@angular-devkit/build-angular:browser-esbuild",` in angular.json
3. Start the app 
4. An error logged in the console `Class constructor ErrorHandler cannot be invoked without 'new'`

Btw, it works great with the `"builder": "@angular-devkit/build-angular:browser",` 

### Environment
* Bugsnag version: 7.22.2
* bugsnag/plugin-angular: 7.22.2,
* Browser framework version (if any):
    * Angular: 17.0.7
* Browser version (e.g. chrome, safari):
* Device (e.g. iphonex):

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [x] Link to it here:
https://stackblitz.com/edit/angular-ivy-7x7fkm?file=src%2Fapp%2Fapp.module.ts
### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```
Class constructor ErrorHandler cannot be invoked without 'new'
```
</details>

**Comment by mivanyna** [comment]
Hi @mclack,
I run `yarn start` which is `ng serve --hmr --port 3000 --open=true`.
I don't change anything else when I switch to `"builder": "@angular-devkit/build-angular:browser"`
Yes, the error stops when comment out ```{ provide: ErrorHandler, useFactory: errorHandlerFactory },```

Maybe something to mention is in my `angular.json` is `"aot": true,`
```
"serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
...
}
```
Can't share the project.

I've found a workaround: 
```
{ provide: ErrorHandler, useClass: AppErrorHandler}

...

export class AppErrorHandler implements ErrorHandler {
   handleError(error: any) {
    Bugsnag.notify(error)
    console.error(error)
  }
}

```
Please let me know if you need something else from me.

**Comment by mivanyna** [comment]
tsconfig is:
```
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "es2020",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "lib": [
      "es2015",
      "es2016",
      "dom",
      "esnext"
    ],
    "noImplicitAny": true,
    "downlevelIteration": true,
    "suppressImplicitAnyIndexErrors": true,
    "ignoreDeprecations": "5.0",
    "noUnusedParameters": true,
    "strictNullChecks": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "typeRoots": [
      "./node_modules/@types"
    ],
    "useDefineForClassFields": false
  },
  "files": [
    "app/main.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.d.ts"
  ]
}

```

**Comment by mivanyna** [comment]
Hi @mclack, have added the link to the project `https://stackblitz.com/edit/angular-ivy-7x7fkm?file=src%2Fapp%2Fapp.module.ts`

**Comment by mivanyna** [comment]
Hi, are there any updates?

**Comment by pumpernikiell** [comment]
Hi, I have the same issue after upgrading to the angular 17 error is thrown:
`TypeError: Class constructor ErrorHandler cannot be invoked without 'new'
    at new BugsnagErrorHandler2 (index.js:28:28)
    at new CustomErrorHandler (CustomErrorHandler.ts:7:5)
    at Object.customErrorHandlerFactory [as useFactory] (app.module.ts:30:10)
    at Object.factory (core.mjs:6288:38)
    at core.mjs:6189:43
    at runInInjectorProfilerContext (core.mjs:867:9)
    at R3Injector.hydrate (core.mjs:6188:17)
    at R3Injector.get (core.mjs:6058:33)
    at injectInjectorOnly (core.mjs:911:40)
    at ɵɵinject (core.mjs:917:42)`

**Comment by mivanyna** [comment]
Hi @mclack do you need anything else from my side for this issue?

**Comment by mclack** [comment]
Hi @mivanyna and @pumpernikiell 

Please accept our apologies for the delay in response here.

We are investigating this now, and will post any updates or questions on this thread as soon as we have them.

Thank you for your patience.

**Comment by mivanyna** [comment]
No rush? We can live w/o good error logging :)

**Comment by mclack** [comment]
Hi @mivanyna and @pumpernikiell

Thanks for your continued patience while we've investigated this issue.

We were unable to reproduce the error on our end, both using a separate Angular 17 app, and the app provided by @mivanyna.

@mivanyna, is the code you've shared up to date, and are the dependencies exactly the same as you're currently using in your app? When we've tried to run the repro code, we got dependency conflicts between Angular 17 and several other dependencies. Could you please tell us more about how you've upgraded your app, and which version you used prior to Angular 17?

@pumpernikiell could you also let us know which version of Angular you have upgraded from? Would you also be willing to share an app which reproduces this error, similar to the one [here](https://stackblitz.com/edit/angular-ivy-7x7fkm?file=src%2Fapp%2Fapp.module.ts)?

**Comment by mivanyna** [comment]
Hi @mclack , I'm opening the provided link and it's still reproducing: 
![image](https://github.com/bugsnag/bugsnag-js/assets/10868397/4e86c808-834f-4761-961c-b2c378d81de2)

There is an error logged in the console.

**Comment by mclack** [comment]
Hi @mivanyna 

Thank you for the clarification.

After looking into this a bit more, we've realised that this error does indeed appear when opening the app on StackBlitz. However, we initially downloaded the app and attempted to build/run this locally, and when doing this, we noticed different errors which were regarding dependency conflicts instead.

Due to the above, we believe that this issue could be due to the dependency conflicts we have observed, and it's possible that the debugging mechanisms on StackBlitz are potentially hiding these conflicts.

- Can you confirm whether you have only seen this error when running the app within StackBlitz?
- Am I right in thinking you upgraded your app to Angular 17 from a different version? If so, did you only begin to see this error after upgrading?
- Can you run this locally and let us know whether you see different errors? If so, would you be able to resolve any dependency conflicts, and then attempt to run this on StackBlitz again?

**Comment by mivanyna** [comment]
Hi @mclack,

This error appears only after the start of the app.
Yes, I have upgraded from angular 16 to angular 17. 
**Please read the steps in the issue and following my answers**:
step 2: `Set "builder": "@angular-devkit/build-angular:browser-esbuild", in angular.json`
Just create a simple project and follow the steps, please.
Everything is specified in the issue [here](https://github.com/bugsnag/bugsnag-js/issues/2057#issue-2050976917) and in comments below.

**Comment by mivanyna** [comment]
Hi @mclack, 

This is what you need to do for the downloaded project:
1. Update **angular** and **bugsnag** to the latest version in package.json
2. Use `yarn` to install 
3. _styles.scss_ - remove imports of the styles - it should be empty
4. tscongif.json - change "target": "ES2022",
5. start the app using `yarn start`
6. open the [http://localhost:4200/](http://localhost:4200/)
7. check in the browser's console the error:
<img width="573" alt="image" src="https://github.com/bugsnag/bugsnag-js/assets/10868397/d194308b-d57f-4f2b-82c0-3caa0f4eb3f1">


Please let me know if there are any questions

**Comment by mclack** [comment]
Hi @mivanyna 

Thank you for your patience here.

We have been able to reproduce the error you were seeing, and have made the necessary changes on the StackBlitz project you provided in order to fix all the errors appearing in the console.

The issue seems like it was down to using the old `NgModule` rather than standalone components. As suggested by the error message, this meant that the `new` keyword is required before invoking `ErrorHandler`. In your `app.module.ts`, you should edit the `NgModule` so that `providers` looks like:
`providers:[{ provide: new ErrorHandler, useFactory: errorHandlerFactory }]`

You are likely to run into some more errors after this. If so, this should be fixed by adding `@bugsnag/js` inside `allowedCommonJsDependencies` within your `angular.json`. This will look something like:
```
"architect": {
...
          "options": {
            "allowedCommonJsDependencies": [
              "@bugsnag/js"
            ],
...
```

Please try the recommendations above and let us know whether that solves the problem.

**Comment by mivanyna** [comment]
it works, thanks

**Comment by pumpernikiell** [comment]
Hi! 
I've applied your solution @mclack - it fixes problem with the error handler, but right now any errors are not sent to the bugsnag

**Comment by mclack** [comment]
Hi @pumpernikiell 

Are you experiencing any other errors in your app? Can you also check whether any network requests are being made to BugSnag? If so, what are the status of these requests? E.g. 200 (Accepted), 408 (Request Timeout). Additionally, can you please check whether the requests are being made to https://notify.bugsnag.com/.

If you're not doing this already, could you also please try [sending a handled event to BugSnag](https://docs.bugsnag.com/platforms/javascript/angular/reporting-handled-errors/#basic-usage) and let us know the outcome of this.

If you're not seeing any requests being made, could you please share some code snippets of how you have configured BugSnag in your app? As this is a public thread, please feel free to open a ticket with us directly by contacting support@bugsnag.com.

**Comment by JJWesterkampAtEndeavour** [comment]
I'm experiencing the same issue.

FWIW: The issue appears to be caused by the following two factors:

1. The build for my angular application literally _imports_ `ErrorHandler` from `@angular/core`. At runtime the @angular/core/fesm2022/core.mjs is resolved for this import, which provides ErrorHandler as a class.

2. The resolved module for `@bugsnag/plugin-angular` is in my case `@bugsnag/plugin-angular/dist/esm5/index.js`, which has the following code in it:

```javascript
import { ErrorHandler, Injectable } from '@angular/core';
import Bugsnag, { Client } from '@bugsnag/js';
// zones are optional, so we need to detect if they are being used
// see https://angular.io/guide/zone#noopzone
var isNgZoneEnabled = typeof Zone !== 'undefined' && !!Zone.current;
var BugsnagErrorHandler = /** @class */ (function (_super) {
    __extends(BugsnagErrorHandler, _super);
    function BugsnagErrorHandler(client) {
        var _this = _super.call(this) || this;
        if (client) {
            _this.bugsnagClient = client;
        }
        else {
            _this.bugsnagClient = Bugsnag._client;
        }
        return _this;
    }
    BugsnagErrorHandler.prototype.handleError = function (error) {
        var handledState = {
            severity: 'error',
            severityReason: { type: 'unhandledException' },
            unhandled: true
        };
        var event = this.bugsnagClient.Event.create(error, true, handledState, 'angular error handler', 1);
        if (error.ngDebugContext) {
            event.addMetadata('angular', {
                component: error.ngDebugContext.component,
                context: error.ngDebugContext.context
            });
        }
        this.bugsnagClient._notify(event);
        ErrorHandler.prototype.handleError.call(this, error);
    };
    BugsnagErrorHandler = __decorate([
        Injectable(),
        __metadata("design:paramtypes", [Client])
    ], BugsnagErrorHandler);
    return BugsnagErrorHandler;
}(ErrorHandler));
export { BugsnagErrorHandler };
```

The error is thrown at the line `var _this = _super.call(this) || this;` in the constructor function. That calls `_super` without `new` which is illegal because `_super` is the resolved ErrorHandler class.

**Comment by mclack** [comment]
Hi @JJWesterkampAtEndeavour 

Thanks for highlighting that.

We are looking into the `fesm` distribution, and have added a task to our backlog to include this. As such, I'm going to reopen this issue, and while we don't currently have an ETA, we will make sure to share any updates when we have them.

**Comment by JesperHonders** [comment]
@mclack is there any update on this? I have this problem on several projects and this is preventing me from an essential upgrade.

**Comment by mclack** [comment]
Hi @JesperHonders 

There is currently no update for an ETA we can share on this, but we do have some tasks lined up regarding JavaScript modules, and adding an `fesm` distribution for Angular is included in this upcoming work.

We will make sure to post any further updates on this thread as they become available. Thanks for your patience in the meantime.

**Comment by JJWesterkampAtEndeavour** [comment]
@mclack Could you please update us on this? We're starting to get stuck with EOL angular versions because of this. I prefer to not have to implement hacky workarounds in all our projects.

Thanks!

**Comment by RobertoSmartBear** [comment]
Hi @JJWesterkampAtEndeavour,

This has been fixed in [bugsnag-js v8.2.0](https://github.com/bugsnag/bugsnag-js/releases/tag/v8.2.0).

If you experience new issues, please feel free to reach out again. Alternatively, you can also open a ticket with us directly by contacting [support@bugsnag.com](mailto:support@bugsnag.com) if you have any other questions, or would like assistance with anything else.
