### ISSUE TITLE
Bugsnag-angular and Bugsnag-js don't play nice with Angular Server-Side-Rendering

### ISSUE THREAD

**Issue by MTRNord** [bugsnag/bugsnag-js#326]
### Expected behavior
To work just fine

### Observed behavior
It transpiles fines but than crashes starting the Server with the following error:

```
$ node dist/server.js
+-------------------------------------------------------------+
  Bugsnag Error: "bugsnag-js" is for browser JavaScript only.
  For node, use the "bugsnag" package.
+-------------------------------------------------------------+
C:\Users\marce\WebstormProjects\SocialNetworksNews-Web2\dist\server.js:142424
!function(n,e){for(var t in e)n[t]=e[t]}(exports,function(n){var e={};function t(l){if(e[l])return e[l].exports;var i=e[l]={i:l,l:!1,exports:{}};return n[l].call(i.exports,i,i.exports,t),i.l=!0,i.exports}return t.m=n,t.c=e,t.d=function(n,e,l){t.o(n,e)||Object.defin
eProperty(n,e,{configurable:!1,enumerable:!0,get:l})},t.n=function(n){var e=n&&n.__esModule?function(){return n.default}:function(){return n};return t.d(e,"a",e),e},t.o=function(n,e){return Object.prototype.hasOwnProperty.call(n,e)},t.p="",t(t.s=0)}({"+ld8":functio
n(n,e,t){"use strict";e.styles=[""]},"/0IM":function(n,e,t){"use strict";Object.defineProperty(e,"__esModule",{value:!0});var l=t("0BRu"),i={hover:["mouseover","mouseout"],focus:["focusin","focusout"]};function o(n,e){void 0===e&&(e=i);var t=(n||"").trim();if(0===t
.length)return[];var o=t.split(/\s+/).map(function(n){return n.split(":")}).map(function(n){var t=e[n[0]]||n;return new l.Trigger(t[0],t[1])}),r=o.fi

TypeError: t(...).default is not a function
    at Object.aR8+ (C:\Users\marce\WebstormProjects\SocialNetworksNews-Web2\dist\server.js:142424:127560)
    at t (C:\Users\marce\WebstormProjects\SocialNetworksNews-Web2\dist\server.js:142424:158)
    at Object.JwoV (C:\Users\marce\WebstormProjects\SocialNetworksNews-Web2\dist\server.js:142424:85409)
    at t (C:\Users\marce\WebstormProjects\SocialNetworksNews-Web2\dist\server.js:142424:158)
    at Object.Zq8w (C:\Users\marce\WebstormProjects\SocialNetworksNews-Web2\dist\server.js:142424:112019)
    at t (C:\Users\marce\WebstormProjects\SocialNetworksNews-Web2\dist\server.js:142424:158)
    at Object.0 (C:\Users\marce\WebstormProjects\SocialNetworksNews-Web2\dist\server.js:142424:6399)
    at t (C:\Users\marce\WebstormProjects\SocialNetworksNews-Web2\dist\server.js:142424:158)
    at n.+ld8.e.styles (C:\Users\marce\WebstormProjects\SocialNetworksNews-Web2\dist\server.js:142424:506)
    at Object.defineProperty.value (C:\Users\marce\WebstormProjects\SocialNetworksNews-Web2\dist\server.js:142424:515)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### Steps to reproduce
It should be reproducable with a normal setup Angular Server Side Rendering and added Bugsnag. No special code required to let this happen

### Version
```
"bugsnag-angular": "^2.0.0",
"bugsnag-js": "^4.2.0",
```

### Additional information
My bugsnagClient config:
```
// configure Bugsnag ASAP, before any other imports
const bugsnagClient = bugsnag({
  apiKey: 'REDACTED',
  appVersion: '0.0.1',
  autoCaptureSessions: true,
  releaseStage: 'development',
  notifyReleaseStages: [ 'development', 'production'],
});
```

If you have any additional Questions feel free to ask

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by bengourley** [comment]
Hi @MTRNord! Sorry for the delay in getting back to you and thanks for your patience.

bugsnag-js is specific to browsers (at the moment) so it won't be able to help with things rendered on the server.

For anything that runs on a node server, you will need to integrate [bugsnag (node)](https://github.com/bugsnag/bugsnag-node). You should be able to detect when the execution environment is on the server and load the node module instead.

In the future we intend to merge the two bugsnag modules into a "universal" package which can run anwhere, and issues like this don't happen.

**Comment by MTRNord** [comment]
@bengourley hm yeah I guess than I need to use both. I will try that. thanks for the reply
