### ISSUE TITLE
 Network Error on BugSnag Test

### ISSUE THREAD

**Issue by simkessy** [bugsnag/bugsnag-js#862]
I wrote this test around bugsnag but it's making network calls in jenkins. How can I prevent this

```
import React from 'react';
import { render } from '@testing-library/react';
import { BugSnag } from './BugSnag';

const BadComponent = () => {
  return new Error();
};

describe('error boundary - bugsnag', () => {
  it('displays errorMessage', () => {
    const { getByText } = render(
      <BugSnag>
        <BadComponent />
      </BugSnag>
    );

    const error = getByText(/slack channel/i);
    expect(error).toBeTruthy();
  });
});
```

```
16:47:27 Summary of all failing tests
16:47:27 FAIL src/utils/tests/ErrorBoundary.test.jsx
16:47:27   ● <ErrorBoundary/> › renders nothing when no error
16:47:27 
16:47:27     Network Error
16:47:27 
16:47:27       at createError (node_modules/axios/lib/core/createError.js:16:15)
16:47:27       at XMLHttpRequest.handleError (node_modules/axios/lib/adapters/xhr.js:83:14)
16:47:27       at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
16:47:27       at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:315:27)
16:47:27       at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:266:3)
16:47:27       at XMLHttpRequestEventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:212:11)
16:47:27       at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:17:36)
16:47:27       at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:127:3)
16:47:27       at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:57:3)
16:47:27       at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:675:20)
16:47:27       at Request.onRequestError (node_modules/request/request.js:877:8)
```

**Comment by mattdyoung** [comment]
Hi @simkessy 

I'm not clear what you're trying to test here or how it's related to Bugsnag.

None of the code snippet you've shared is using bugsnag-js, it looks like you've defined your own component `BugSnag` but not shared the code for that.

If you believe this is evidence of a bug in the bugsnag-js library we'd need you to share a full downloadable reproduction example and let us know what aspect of the behavior is unexpected.

**Comment by simkessy** [comment]
@mattdyoung the component is just a wrapper around BugSnag. Here's the code: 

```
import React from 'react';
import Bugsnag from '@bugsnag/browser';
import BugsnagPluginReact from '@bugsnag/plugin-react';
import { Box, Text, Layer, Modal, Divider } from 'gestalt';
import packageJson from '../../../package.json';
// Config options: https://docs.bugsnag.com/platforms/javascript/react/configuration-options/
export const bugsnagClient = Bugsnag.start({
  apiKey: '9...,
  appVersion: packageJson.version,
  appType: 'client',
  filters: [
    'access_token', // exact match: "access_token"
    /^password$/i, // case-insensitive: "password", "PASSWORD", "PaSsWoRd"
    /^cc_/ // prefix match: "cc_number" "cc_cvv" "cc_expiry"
  ],
  releaseStage: ENVIRONMENT,
  beforeNotify: data => {
    data.metaData.sessionURL = LogRocketInstance.sessionURL;
    return data;
  },
  plugins: [new BugsnagPluginReact(React)]
});

const ErrorScreen = ({ error }) => {
  return (
    <Box marginLeft={-1} marginRight={-1}>
      <Layer>
        <Modal
          accessibilityModalLabel="Sorry there was an error"
          heading="Sorry there was an error"
          role="alertdialog"
          size="sm">
          <Box paddingX={6} margin={6}>
            <Box marginBottom={3}>
              <Text size="md" align="center">
                {error.message}
              </Text>
            </Box>
            <Divider />
            <Text align="center">
              Please reach out the #ts-tools-xfn slack channel for assistance
            </Text>
          </Box>
        </Modal>
      </Layer>
    </Box>
  );
};

// wrap your entire app tree in the ErrorBoundary provided
const ErrorBoundary = Bugsnag.getPlugin('react');
export const BugSnag = ({ children }) => {
  return <ErrorBoundary FallbackComponent={ErrorScreen}>{children}</ErrorBoundary>;
};
```
